services:
  Controller\AbstractApiController:
    abstract: true
    calls:
      - method: setCurrentUser
        arguments:
          - '@app.current.user'
      - method: setSerializer
        arguments:
          - '@default.serializer'
      - method: setTranslator
        arguments:
          - '@translator'
    public: true

  Controller\UserApiController:
    public: true
    parent: Controller\AbstractApiController

  Controller\PageApiController:
    arguments:
      - '@tactician.commandbus'
      - '@page.repo'
    public: true
    parent: Controller\AbstractApiController

  Controller\AuthApiController:
    arguments:
      - '@tactician.commandbus'
      - '@user.repo'
      - '@user.repo'
    public: true
    parent: Controller\AbstractApiController