security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        api:
          id: app.api_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            provider: api
            guard:
              authenticators:
                  - app.api_authenticator

    access_control:
        - { path: ^/, methods: [OPTIONS], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/register, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/login, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/page, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, roles: ROLE_ADMIN }