services:
  abstract.controller:
    class: App\Controller\AbstractController
    arguments:
      - '@serializer'
      - '@translator'
      - '@App\Entity\User'
  user.controller:
    class: App\Controller\UserController
    arguments:
      - '@app.current.user'
      - '@abstract.controller'
  page.controller:
    class: App\Controller\PageController
    arguments:
      - '@tactician.commandbus'
      - '@page.repo'
      - '@abstract.controller'
  auth.controller:
    class: App\Controller\AuthController
    arguments:
      - '@tactician.commandbus'
      - '@user.repo'
      - '@user.repo'
      - '@abstract.controller'
  default.controller:
    class: App\Controller\DefaultController
    arguments:
      - '@abstract.controller'