services:
  abstract.ctrl:
    class: Controller\AbstractController
    abstract: true
    calls:
      - method: setCurrentUser
        arguments:
          - '@app.current.user'
      - method: setSerializer
        arguments:
          - '@default.serializer'
      - method: setTranslator
        arguments:
          - '@translator'
    public: true

  Controller\UserController:
    public: true
    parent: abstract.ctrl

  Controller\PageController:
    arguments:
      - '@tactician.commandbus'
      - '@page.repo'
    public: true
    parent: abstract.ctrl

  Controller\AuthController:
    arguments:
      - '@tactician.commandbus'
      - '@user.repo'
      - '@user.repo'
    public: true
    parent: abstract.ctrl