services:

  Controller\AbstractController:
    arguments:
      - '@serializer'
      - '@translator'
      - '@app.current.user'
    public: true

  Controller\UserController:
    arguments:
      - '@app.current.user'
      - '@Controller\AbstractController'
    public: true

  Controller\PageController:
    arguments:
      - '@tactician.commandbus'
      - '@page.repo'
      - '@Controller\AbstractController'
    public: true

  Controller\AuthController:
    arguments:
      - '@tactician.commandbus'
      - '@user.repo'
      - '@user.repo'
      - '@Controller\AbstractController'
    public: true