services:

    user.register:
        class: Handlers\User\UserRegisterHandler
        arguments:
            - '@user.repo'
        tags:
            - { name: tactician.handler, command: Commands\User\UserRegisterCommand }
    page.edit:
        class: Handlers\Page\PageHandler
        arguments:
          - '@page.repo'
          - '@page.repo'
        tags:
            - { name: tactician.handler, command: Commands\Page\PageCommand }
    page.delete:
        class: Handlers\Page\PageDeleteHandler
        arguments:
          - '@page.repo'
          - '@page.repo'
        tags:
            - { name: tactician.handler, command: Commands\Page\PageDeleteCommand }