services:

    user.register:
        class: App\Handlers\UserRegisterHandler
        arguments:
            - '@user.repo'
        tags:
            - { name: tactician.handler, command: App\Commands\UserRegisterCommand }
    page.edit:
        class: App\Handlers\Page\PageHandler
        arguments:
          - '@page.repo'
          - '@page.repo'
        tags:
            - { name: tactician.handler, command: App\Commands\Page\PageCommand }
    page.delete:
        class: App\Handlers\Page\PageDeleteHandler
        arguments:
          - '@page.repo'
          - '@page.repo'
        tags:
            - { name: tactician.handler, command: App\Commands\Page\PageDeleteCommand }