services:
    user.repo:
      class: Repository\User\UserRepository
      arguments:
        - '@doctrine.orm.entity_manager'

    page.repo:
      class: Repository\Page\PageRepository
      arguments:
        - '@doctrine.orm.entity_manager'