services:
    abstract.repo:
      abstract: true
      class: Domain\Shared\Repository\AbstractRepository
      arguments:
        - '@doctrine.orm.entity_manager'

    user.repo:
      class: Domain\User\Repository\UserRepository
      parent: abstract.repo

    page.repo:
      class: Domain\Page\Repository\PageRepository
      parent: abstract.repo