services:
    abstract.repo:
      abstract: true
      class: Repository\AbstractRepository
      arguments:
        - '@doctrine.orm.entity_manager'

    user.repo:
      class: Repository\User\UserRepository
      arguments:
        - '@doctrine.orm.entity_manager'

    page.repo:
      class: Repository\Page\PageRepository
      arguments:
        - '@doctrine.orm.entity_manager'