index:
    path: /
    controller: App\Controller\DefaultController::index
register:
    path: /auth/register
    controller: App\Controller\AuthController::register
    methods: [POST]
login:
    path: /auth/login
    controller: App\Controller\AuthController::login
    methods: [POST]