index:
    path: /
    controller: App\Controller\DefaultController::index
register:
    path: /auth/register
    controller: App\Controller\AuthController::register
    methods: [POST]
login:
    path: /auth/login
    controller: App\Controller\AuthController::login
    methods: [POST]
logout:
    path: /auth/logout
    controller: App\Controller\AuthController::logout
    methods: [POST]
defaultPage:
    path: /page/default
    controller: App\Controller\PageController::index
    methods: [GET]
getPage:
    path: /page/{slug}
    controller: App\Controller\PageController::getPage
    methods: [GET]
    requirements:
      slug: '*.'