Domain\User\Entity\User:
    attributes:
        userId:
            groups: ['user-public']
        username:
            groups: ['user-public']
        email:
            groups: ['user-public']
        roles:
            groups: ['user-public']
        apiToken:
            groups: ['user-public']

Domain\User\Entity\Roles:
    attributes:
        list:
            groups: ['user-public']

Domain\User\Entity\ApiToken:
    attributes:
        key:
            groups: ['user-public']

Domain\Page\Entity\Page:
    attributes:
        pageId:
            groups: ['page-list']
        parentPageId:
            groups: ['page-list']
        slug:
            groups: ['page-list']
        title:
            groups: ['page-list']
        content:
            groups: ['page-list']
        isDefault:
            groups: ['page-list']
        showInMenu:
            groups: ['page-list']
        createdAt:
            groups: ['page-list']
        updatedAt:
            groups: ['page-list']