Entity\User:
    attributes:
        userId:
            groups: ['user-public']
        username:
            groups: ['user-public']
        email:
            groups: ['user-public']
        roles:
            groups: ['user-public']
        apiToken:
            groups: ['user-public']

Entity\Roles:
    attributes:
        list:
            groups: ['user-public']

Entity\ApiToken:
    attributes:
        key:
            groups: ['user-public']

Entity\Page:
    attributes:
        pageId:
            groups: ['page-list']
        slug:
            groups: ['page-list']
        title:
            groups: ['page-list']
        content:
            groups: ['page-list']
        isDefault:
            groups: ['page-list']
        parentPageId:
            groups: ['page-list']