Entity\User:
    attributes:
        userId:
            groups: ['user-public']
        username:
            groups: ['user-public']
        email:
            groups: ['user-public']
        roles:
            groups: ['user-public']
        apiToken:
            groups: ['user-public']

Entity\Roles:
    attributes:
        list:
            groups: ['user-public']

Entity\ApiToken:
    attributes:
        key:
            groups: ['user-public']