services:
    app.exceprion.listener:
      class: Application\Listeners\ExceptionListener
      arguments:
        - '@translator'
      tags:
          - { name: kernel.event_listener, event: kernel.exception }

    app.request_listener:
      class: Application\Listeners\HttpRequestListener
      tags:
        - { name: kernel.event_listener, event: kernel.request }

    app.api_authenticator:
      class: Security\Authentication\ApiTokenAuthenticator
      arguments: ['@user.repo']

    app.api_user_provider:
      class: Security\Authentication\ApiUserProvider
      arguments: ['@user.repo']

    app.current.user.factory:
      class: Security\Authentication\CurrentUserFactory
      arguments:
        - '@security.token_storage'

    app.current.user:
      class: Entity\User
      factory: ['@app.current.user.factory', getUser]